[package]
name = "bsuir-rt-utils"
version = "3.0.0"
edition = "2021"

[dependencies]
dircpy = { version = "*" }
symlink = { version = "*" }
expanduser = { version = "*" }
pest = { version = "*" }
pest_derive ={ version = "*" }
